// ─────────────────────────────────────────────────────────────────────────────
// Bandit Recycling — Baler Database
// Wire specs keyed to Bandit product catalog:
//   "single-loop"   → Single Loop Bale Ties  (11ga or 13ga, black annealed)
//   "double-loop"   → Double Loop Bale Ties  (11ga, black annealed)
//   "auto-tie-box"  → Auto-Tie Box Wire       (14ga or 16ga, galvanized)
// ─────────────────────────────────────────────────────────────────────────────

export type BalerType = "vertical" | "horizontal" | "two-ram";
export type WireFormat = "single-loop" | "double-loop" | "auto-tie-box";
export type BalerTier = "entry" | "mid" | "commercial" | "industrial";

export interface Baler {
  id: string;
  make: string;
  model: string;
  fullName: string;
  type: BalerType;
  tier: BalerTier;
  /** Nominal bale width in inches */
  baleWidth: number;
  /** Nominal bale depth in inches */
  baleDepth: number;
  /** Approx bale weight range in lbs */
  baleWeightMin: number;
  baleWeightMax: number;
  motorHP: string;
  wireFormat: WireFormat;
  /** e.g. "11 ga" or "14–16 ga" */
  wireGauge: string;
  wireFinish: "black-annealed" | "galvanized" | "either";
  wiresPerBale: number;
  /** Bandit wire product anchor on /wire page */
  wireProductAnchor: string;
  commonMaterials: string[];
  typicalUsers: string[];
  /** e.g. "2–5 tons/day" */
  throughput: string;
  features: string[];
  serviceNotes: string;
  discontinued?: boolean;
  tags?: string[];
}

// ─── MAKE METADATA ───────────────────────────────────────────────────────────
export const MAKES: Record<string, { origin: string; founded?: string; specialty: string; serviceNote: string }> = {
  "Harmony Enterprise": {
    origin: "USA",
    founded: "1980",
    specialty: "Vertical balers for retail and light commercial",
    serviceNote: "Simple hydraulic systems; parts widely available. Common in grocery and big-box retail.",
  },
  "Bramidan": {
    origin: "Denmark",
    founded: "1997",
    specialty: "Compact vertical balers for small-medium business",
    serviceNote: "European electrical components; some specialty parts. Reliable units with good safety features.",
  },
  "PTR Baler & Compactor": {
    origin: "USA",
    founded: "1946",
    specialty: "Vertical and horizontal balers for retail and distribution",
    serviceNote: "Long-established brand with broad model range. Parts generally available through distributors.",
  },
  "Mil-tek": {
    origin: "Denmark",
    founded: "1992",
    specialty: "Pneumatic vertical balers for small business",
    serviceNote: "Pneumatic (air-powered) design — no hydraulic fluid. Requires compressed air supply.",
  },
  "Marathon Equipment": {
    origin: "USA",
    founded: "1984",
    specialty: "Vertical balers and compactors for retail/hospitality",
    serviceNote: "Acquired by Dover Corp. Parts support excellent. Very common in SE US.",
  },
  "American Baler": {
    origin: "USA",
    founded: "1945",
    specialty: "Heavy-duty horizontal balers for recycling operations",
    serviceNote: "Robust construction; older units are serviceable but parts lead times can be long.",
  },
  "Harris": {
    origin: "USA",
    founded: "1894",
    specialty: "Industrial horizontal and two-ram balers",
    serviceNote: "Industry flagship — strong dealer network in SE US. Excellent parts availability.",
  },
  "International Baler": {
    origin: "USA",
    founded: "1973",
    specialty: "Horizontal balers for MRF and recycling centers",
    serviceNote: "Made in Jacksonville, FL — strong SE US presence. Good parts and support.",
  },
  "Maren Engineering": {
    origin: "USA",
    founded: "1948",
    specialty: "Horizontal balers for paper and plastics recycling",
    serviceNote: "Long-running models; robust frames. Parts availability varies by age.",
  },
  "Balemaster": {
    origin: "USA",
    founded: "1957",
    specialty: "Horizontal and vertical balers for light industrial",
    serviceNote: "Good entry-level commercial units. Common in grocery distribution and small MRFs.",
  },
  "Bollegraaf": {
    origin: "Netherlands",
    founded: "1961",
    specialty: "High-throughput horizontal and two-ram balers for large MRFs",
    serviceNote: "Premium European equipment. Specialized tech support may be needed; parts import times vary.",
  },
  "Macpresse": {
    origin: "France",
    founded: "1972",
    specialty: "Horizontal channel balers for paper and plastics",
    serviceNote: "French-built; reliable channel baler design. Common in newspaper and OCC operations.",
  },
  "IPS Balers": {
    origin: "USA",
    specialty: "Mid-range horizontal balers for recycling and distribution",
    serviceNote: "Good value horizontal line; parts support improving. SE-focused dealer network.",
  },
  "Sebright Products": {
    origin: "USA",
    founded: "1948",
    specialty: "Vertical and horizontal balers for industrial waste",
    serviceNote: "Sturdy construction; common in manufacturing and distribution. Parts generally available.",
  },
  "Global Baler": {
    origin: "USA",
    specialty: "Economy vertical balers for small business",
    serviceNote: "Economy-tier equipment; simpler hydraulics. Good for low-volume retail applications.",
  },
  "Excel Baler": {
    origin: "USA",
    specialty: "Vertical balers for light commercial",
    serviceNote: "Entry-level units common in small retail. Straightforward repairs.",
  },
  "Pakrite": {
    origin: "USA",
    specialty: "Vertical balers for retail and grocery",
    serviceNote: "Solid mid-range vertical line; good parts availability.",
  },
};

// ─── BALER DATA ───────────────────────────────────────────────────────────────
export const BALERS: Baler[] = [

  // ══ HARMONY ENTERPRISE — VERTICAL ════════════════════════════════════════
  {
    id: "harmony-25",
    make: "Harmony Enterprise",
    model: "25",
    fullName: "Harmony Enterprise Model 25",
    type: "vertical",
    tier: "entry",
    baleWidth: 25,
    baleDepth: 30,
    baleWeightMin: 75,
    baleWeightMax: 200,
    motorHP: "3 HP",
    wireFormat: "single-loop",
    wireGauge: "13 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 2,
    wireProductAnchor: "single-loop",
    commonMaterials: ["OCC / Cardboard", "Newspaper", "Office Paper", "Soft Plastics"],
    typicalUsers: ["Convenience stores", "Small retail", "Restaurants", "Offices"],
    throughput: "< 0.5 ton/day",
    features: ["Manual tie", "Top-loading", "No pit required", "3 HP motor", "Compact 36\" footprint"],
    serviceNotes: "Entry-level unit with straightforward hydraulics. Common cylinder seal failures around 5–8 years.",
    tags: ["cardboard", "retail", "small"],
  },
  {
    id: "harmony-30",
    make: "Harmony Enterprise",
    model: "30",
    fullName: "Harmony Enterprise Model 30",
    type: "vertical",
    tier: "entry",
    baleWidth: 30,
    baleDepth: 36,
    baleWeightMin: 150,
    baleWeightMax: 350,
    motorHP: "5 HP",
    wireFormat: "single-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 3,
    wireProductAnchor: "single-loop",
    commonMaterials: ["OCC / Cardboard", "Newspaper", "Mixed Paper", "PET Bottles"],
    typicalUsers: ["Grocery stores", "Big-box retail", "Distribution centers"],
    throughput: "0.5–1.5 ton/day",
    features: ["Manual tie", "Top-loading", "5 HP motor", "Safety interlock door"],
    serviceNotes: "Very common in SE US grocery operations. High-cycle units need annual PM.",
    tags: ["cardboard", "grocery", "retail"],
  },
  {
    id: "harmony-45",
    make: "Harmony Enterprise",
    model: "45",
    fullName: "Harmony Enterprise Model 45",
    type: "vertical",
    tier: "mid",
    baleWidth: 45,
    baleDepth: 48,
    baleWeightMin: 300,
    baleWeightMax: 700,
    motorHP: "7.5 HP",
    wireFormat: "double-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 3,
    wireProductAnchor: "double-loop",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "Aluminum Cans", "PET / HDPE Plastics"],
    typicalUsers: ["Supermarkets", "Warehouses", "Light manufacturing"],
    throughput: "1–3 ton/day",
    features: ["Manual tie", "High-density ram", "7.5 HP motor", "Side-ejection option"],
    serviceNotes: "Mid-range workhorse; hydraulic pump and valve issues are most common service calls.",
    tags: ["cardboard", "plastic", "mid-volume"],
  },
  {
    id: "harmony-60",
    make: "Harmony Enterprise",
    model: "60",
    fullName: "Harmony Enterprise Model 60",
    type: "vertical",
    tier: "commercial",
    baleWidth: 60,
    baleDepth: 48,
    baleWeightMin: 500,
    baleWeightMax: 1000,
    motorHP: "10 HP",
    wireFormat: "double-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 4,
    wireProductAnchor: "double-loop",
    commonMaterials: ["OCC / Cardboard", "Plastics (PET/HDPE)", "Aluminum", "Mixed Paper"],
    typicalUsers: ["Distribution centers", "Large retail chains", "Industrial facilities"],
    throughput: "2–5 ton/day",
    features: ["Auto-eject available", "Dual ram", "10 HP motor", "High-density bales"],
    serviceNotes: "High-tonnage vertical. Cylinder rod and seal wear increases with volume. Annual PM strongly recommended.",
    tags: ["cardboard", "high-volume", "commercial"],
  },
  {
    id: "harmony-72",
    make: "Harmony Enterprise",
    model: "72",
    fullName: "Harmony Enterprise Model 72",
    type: "vertical",
    tier: "commercial",
    baleWidth: 72,
    baleDepth: 48,
    baleWeightMin: 700,
    baleWeightMax: 1400,
    motorHP: "15 HP",
    wireFormat: "double-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 5,
    wireProductAnchor: "double-loop",
    commonMaterials: ["OCC / Cardboard", "Corrugated", "Plastics", "Mixed Recyclables"],
    typicalUsers: ["Large distribution centers", "Fulfillment centers", "Grocery chains"],
    throughput: "3–8 ton/day",
    features: ["Auto-eject", "High-density 15 HP", "5-wire configuration", "Extended stroke"],
    serviceNotes: "Largest of the Harmony vertical line. High-cycle units need quarterly PM schedules.",
    tags: ["cardboard", "high-volume", "commercial", "fulfillment"],
  },

  // ══ BRAMIDAN — VERTICAL ═══════════════════════════════════════════════════
  {
    id: "bramidan-b3",
    make: "Bramidan",
    model: "B3",
    fullName: "Bramidan B3",
    type: "vertical",
    tier: "entry",
    baleWidth: 24,
    baleDepth: 32,
    baleWeightMin: 60,
    baleWeightMax: 175,
    motorHP: "3 HP",
    wireFormat: "single-loop",
    wireGauge: "13 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 2,
    wireProductAnchor: "single-loop",
    commonMaterials: ["OCC / Cardboard", "Newspapers", "Soft Plastics"],
    typicalUsers: ["Small retail", "Cafes", "Offices", "Hotels"],
    throughput: "< 0.3 ton/day",
    features: ["Floor-level loading", "Safety door", "Low noise", "European design", "Compact"],
    serviceNotes: "Reliable European unit. Note: some electrical components are metric/European sourced.",
    tags: ["cardboard", "small", "retail"],
  },
  {
    id: "bramidan-b5",
    make: "Bramidan",
    model: "B5",
    fullName: "Bramidan B5",
    type: "vertical",
    tier: "entry",
    baleWidth: 30,
    baleDepth: 36,
    baleWeightMin: 150,
    baleWeightMax: 350,
    motorHP: "5 HP",
    wireFormat: "single-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 3,
    wireProductAnchor: "single-loop",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "PET Bottles", "Film Plastics"],
    typicalUsers: ["Grocery stores", "Small supermarkets", "Retail chains"],
    throughput: "0.5–1.5 ton/day",
    features: ["Full-door loading", "Integrated wire holder", "LED indicators", "Adjustable bale height"],
    serviceNotes: "Popular in grocery sector. Hydraulic system is compact and well-sealed.",
    tags: ["cardboard", "grocery", "retail"],
  },
  {
    id: "bramidan-b12",
    make: "Bramidan",
    model: "B12",
    fullName: "Bramidan B12",
    type: "vertical",
    tier: "mid",
    baleWidth: 40,
    baleDepth: 48,
    baleWeightMin: 300,
    baleWeightMax: 700,
    motorHP: "7.5 HP",
    wireFormat: "double-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 4,
    wireProductAnchor: "double-loop",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "Plastics", "Aluminum Cans"],
    typicalUsers: ["Supermarkets", "Logistics centers", "Distribution warehouses"],
    throughput: "1–3 ton/day",
    features: ["Auto-tie option", "Integrated scale option", "High-density compression", "Safety certified"],
    serviceNotes: "Mid-range Bramidan with solid reliability record. Watch for door latch wear on high-cycle units.",
    tags: ["cardboard", "grocery", "mid-volume"],
  },
  {
    id: "bramidan-b20",
    make: "Bramidan",
    model: "B20",
    fullName: "Bramidan B20",
    type: "vertical",
    tier: "commercial",
    baleWidth: 44,
    baleDepth: 50,
    baleWeightMin: 450,
    baleWeightMax: 900,
    motorHP: "10 HP",
    wireFormat: "double-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 4,
    wireProductAnchor: "double-loop",
    commonMaterials: ["OCC / Cardboard", "Plastics (PET, HDPE)", "Aluminum", "Steel Cans"],
    typicalUsers: ["Large supermarkets", "Fulfillment centers", "Regional distribution"],
    throughput: "2–5 ton/day",
    features: ["High-density baling", "Auto-eject", "Integrated wire cutter", "Heavy-duty door"],
    serviceNotes: "Commercial-grade Bramidan. High uptime design; monitor hydraulic temperature in FL/GA summer heat.",
    tags: ["cardboard", "high-volume", "commercial"],
  },
  {
    id: "bramidan-b30",
    make: "Bramidan",
    model: "B30",
    fullName: "Bramidan B30",
    type: "vertical",
    tier: "commercial",
    baleWidth: 50,
    baleDepth: 54,
    baleWeightMin: 600,
    baleWeightMax: 1200,
    motorHP: "15 HP",
    wireFormat: "double-loop",
    wireGauge: "11 ga",
    wireFinish: "either",
    wiresPerBale: 5,
    wireProductAnchor: "double-loop",
    commonMaterials: ["OCC / Cardboard", "Corrugated", "Mixed Plastics", "Aluminum"],
    typicalUsers: ["Large distribution centers", "Retail chains", "Industrial operations"],
    throughput: "3–7 ton/day",
    features: ["Largest Bramidan vertical", "High-density 15 HP", "Auto-eject", "Optional weighing system"],
    serviceNotes: "Heavy-duty vertical baler. Requires regular cylinder maintenance at this volume.",
    tags: ["cardboard", "high-volume", "industrial"],
  },

  // ══ PTR BALER & COMPACTOR — VERTICAL ═════════════════════════════════════
  {
    id: "ptr-excel-25",
    make: "PTR Baler & Compactor",
    model: "Excel 25",
    fullName: "PTR Excel 25",
    type: "vertical",
    tier: "entry",
    baleWidth: 25,
    baleDepth: 30,
    baleWeightMin: 75,
    baleWeightMax: 200,
    motorHP: "3 HP",
    wireFormat: "single-loop",
    wireGauge: "13 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 2,
    wireProductAnchor: "single-loop",
    commonMaterials: ["OCC / Cardboard", "Newspaper", "Mixed Paper"],
    typicalUsers: ["Small retailers", "Convenience stores", "Restaurants"],
    throughput: "< 0.5 ton/day",
    features: ["Hand-operated wire system", "Manual tie", "Compact footprint", "Simple controls"],
    serviceNotes: "Long-established PTR unit. Simple design means easy field repairs.",
    tags: ["cardboard", "retail", "entry"],
  },
  {
    id: "ptr-excel-30",
    make: "PTR Baler & Compactor",
    model: "Excel 30",
    fullName: "PTR Excel 30",
    type: "vertical",
    tier: "entry",
    baleWidth: 30,
    baleDepth: 36,
    baleWeightMin: 150,
    baleWeightMax: 350,
    motorHP: "5 HP",
    wireFormat: "single-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 3,
    wireProductAnchor: "single-loop",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "Plastic Film"],
    typicalUsers: ["Grocery stores", "Mid-size retail", "Offices"],
    throughput: "0.5–1.5 ton/day",
    features: ["Full-width loading door", "Safety interlock", "Wire channel guides"],
    serviceNotes: "Very common in SE US retail. Straightforward PM and repair. Bandit stocks common parts.",
    tags: ["cardboard", "grocery", "retail"],
  },
  {
    id: "ptr-700",
    make: "PTR Baler & Compactor",
    model: "700",
    fullName: "PTR 700 Horizontal",
    type: "horizontal",
    tier: "commercial",
    baleWidth: 48,
    baleDepth: 60,
    baleWeightMin: 800,
    baleWeightMax: 1800,
    motorHP: "25 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 4,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "Plastics (PET, HDPE)", "Aluminum"],
    typicalUsers: ["Recycling centers", "Distribution centers", "Paper brokers"],
    throughput: "3–8 ton/day",
    features: ["Auto-tie", "Conveyor feed", "Programmable cycle", "High-density compression"],
    serviceNotes: "PTR's commercial horizontal line. Tie wire head maintenance is the primary service item.",
    tags: ["cardboard", "plastics", "high-volume", "recycling center"],
  },

  // ══ MIL-TEK — VERTICAL (PNEUMATIC) ═══════════════════════════════════════
  {
    id: "miltek-2025",
    make: "Mil-tek",
    model: "2025",
    fullName: "Mil-tek 2025",
    type: "vertical",
    tier: "entry",
    baleWidth: 20,
    baleDepth: 25,
    baleWeightMin: 50,
    baleWeightMax: 130,
    motorHP: "Pneumatic (5–7 bar)",
    wireFormat: "single-loop",
    wireGauge: "13 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 2,
    wireProductAnchor: "single-loop",
    commonMaterials: ["OCC / Cardboard", "Plastic Film", "Newspaper"],
    typicalUsers: ["Small offices", "Cafes", "Boutique retail", "Hotels"],
    throughput: "< 0.25 ton/day",
    features: ["Pneumatic (no hydraulic oil)", "Ultra-compact", "Quiet operation", "ATEX zone safe"],
    serviceNotes: "Requires clean compressed air supply. No hydraulic fluid — different PM than standard balers.",
    tags: ["cardboard", "small", "pneumatic"],
  },
  {
    id: "miltek-2125",
    make: "Mil-tek",
    model: "2125",
    fullName: "Mil-tek 2125",
    type: "vertical",
    tier: "entry",
    baleWidth: 21,
    baleDepth: 25,
    baleWeightMin: 75,
    baleWeightMax: 175,
    motorHP: "Pneumatic (5–7 bar)",
    wireFormat: "single-loop",
    wireGauge: "13 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 2,
    wireProductAnchor: "single-loop",
    commonMaterials: ["OCC / Cardboard", "Plastic Film", "Newspapers"],
    typicalUsers: ["Small retailers", "Food service", "Small manufacturers"],
    throughput: "< 0.4 ton/day",
    features: ["Pneumatic", "Taller chamber than 2025", "Compact footprint", "No hydraulic fluid"],
    serviceNotes: "Medium Mil-tek. Air regulator and cylinder seals are the primary maintenance items.",
    tags: ["cardboard", "small", "pneumatic"],
  },

  // ══ MARATHON EQUIPMENT — VERTICAL ════════════════════════════════════════
  {
    id: "marathon-vs30",
    make: "Marathon Equipment",
    model: "VS30",
    fullName: "Marathon VS30",
    type: "vertical",
    tier: "entry",
    baleWidth: 30,
    baleDepth: 36,
    baleWeightMin: 150,
    baleWeightMax: 375,
    motorHP: "5 HP",
    wireFormat: "single-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 3,
    wireProductAnchor: "single-loop",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "Plastic Film"],
    typicalUsers: ["Retail stores", "Grocery", "Restaurants"],
    throughput: "0.5–1.5 ton/day",
    features: ["Full-door loading", "Manual tie", "5 HP motor", "Compact", "Low maintenance"],
    serviceNotes: "Very common in SE US. Marathon has strong dealer support; Bandit services these frequently.",
    tags: ["cardboard", "grocery", "retail"],
  },
  {
    id: "marathon-vs60",
    make: "Marathon Equipment",
    model: "VS60",
    fullName: "Marathon VS60",
    type: "vertical",
    tier: "mid",
    baleWidth: 60,
    baleDepth: 48,
    baleWeightMin: 500,
    baleWeightMax: 1100,
    motorHP: "10 HP",
    wireFormat: "double-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 4,
    wireProductAnchor: "double-loop",
    commonMaterials: ["OCC / Cardboard", "Mixed Recyclables", "Plastics"],
    typicalUsers: ["Distribution centers", "Large supermarkets", "Industrial"],
    throughput: "2–5 ton/day",
    features: ["High-volume vertical", "10 HP motor", "Auto-eject option", "Heavy-duty door"],
    serviceNotes: "Marathon's heavy vertical line. Used in high-volume grocery distribution across the South.",
    tags: ["cardboard", "high-volume", "commercial"],
  },

  // ══ PAKRITE — VERTICAL ════════════════════════════════════════════════════
  {
    id: "pakrite-pk30",
    make: "Pakrite",
    model: "PK-30",
    fullName: "Pakrite PK-30",
    type: "vertical",
    tier: "entry",
    baleWidth: 30,
    baleDepth: 36,
    baleWeightMin: 125,
    baleWeightMax: 325,
    motorHP: "5 HP",
    wireFormat: "single-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 3,
    wireProductAnchor: "single-loop",
    commonMaterials: ["OCC / Cardboard", "Newspaper", "Office Paper"],
    typicalUsers: ["Retail stores", "Schools", "Offices", "Small warehouses"],
    throughput: "0.5–1 ton/day",
    features: ["Manual tie", "Full-door loading", "Simple controls", "Safety door lock"],
    serviceNotes: "Reliable entry-level vertical. Hydraulic pump wear is the most common issue at 5–7 year mark.",
    tags: ["cardboard", "retail", "entry"],
  },
  {
    id: "pakrite-pk60",
    make: "Pakrite",
    model: "PK-60",
    fullName: "Pakrite PK-60",
    type: "vertical",
    tier: "mid",
    baleWidth: 60,
    baleDepth: 48,
    baleWeightMin: 400,
    baleWeightMax: 900,
    motorHP: "10 HP",
    wireFormat: "double-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 4,
    wireProductAnchor: "double-loop",
    commonMaterials: ["OCC / Cardboard", "Plastics", "Aluminum"],
    typicalUsers: ["Large retail chains", "Warehouses", "Distribution centers"],
    throughput: "2–4 ton/day",
    features: ["Auto-eject", "Heavy-duty ram", "10 HP motor", "Adjustable bale density"],
    serviceNotes: "Mid-range Pakrite. Cylinder and valve issues typical at higher cycle counts.",
    tags: ["cardboard", "commercial", "mid-volume"],
  },

  // ══ SEBRIGHT PRODUCTS — VERTICAL ══════════════════════════════════════════
  {
    id: "sebright-6048",
    make: "Sebright Products",
    model: "6048",
    fullName: "Sebright 6048 Vertical",
    type: "vertical",
    tier: "commercial",
    baleWidth: 60,
    baleDepth: 48,
    baleWeightMin: 500,
    baleWeightMax: 1100,
    motorHP: "10–15 HP",
    wireFormat: "double-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 4,
    wireProductAnchor: "double-loop",
    commonMaterials: ["OCC / Cardboard", "Industrial Waste Paper", "Plastics"],
    typicalUsers: ["Manufacturing plants", "Distribution centers", "Industrial facilities"],
    throughput: "2–5 ton/day",
    features: ["Heavy-gauge steel construction", "Industrial-duty hydraulics", "High-density compression"],
    serviceNotes: "Built for industrial environments. Rugged construction; excellent for manufacturing scrap.",
    tags: ["cardboard", "industrial", "manufacturing"],
  },

  // ══ GLOBAL BALER — VERTICAL ═══════════════════════════════════════════════
  {
    id: "global-gb30",
    make: "Global Baler",
    model: "GB30",
    fullName: "Global Baler GB30",
    type: "vertical",
    tier: "entry",
    baleWidth: 30,
    baleDepth: 32,
    baleWeightMin: 100,
    baleWeightMax: 275,
    motorHP: "5 HP",
    wireFormat: "single-loop",
    wireGauge: "11 ga",
    wireFinish: "black-annealed",
    wiresPerBale: 3,
    wireProductAnchor: "single-loop",
    commonMaterials: ["OCC / Cardboard", "Newspaper"],
    typicalUsers: ["Small retailers", "Convenience stores"],
    throughput: "< 1 ton/day",
    features: ["Economy design", "Manual tie", "Simple hydraulics"],
    serviceNotes: "Economy unit; limited parts support but straightforward design makes field repair easy.",
    tags: ["cardboard", "entry", "retail"],
  },

  // ══ AMERICAN BALER — HORIZONTAL ═══════════════════════════════════════════
  {
    id: "american-72hd",
    make: "American Baler",
    model: "72-HD",
    fullName: "American Baler 72-HD",
    type: "horizontal",
    tier: "commercial",
    baleWidth: 50,
    baleDepth: 60,
    baleWeightMin: 900,
    baleWeightMax: 1800,
    motorHP: "30 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 4,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "PET Bottles", "HDPE", "Aluminum Cans"],
    typicalUsers: ["Recycling centers", "MRFs", "Paper mills", "Plastics reclaimers"],
    throughput: "3–8 ton/day",
    features: ["Auto-tie", "72\" chamber width", "30 HP motor", "Conveyor compatible", "High-density bales"],
    serviceNotes: "American Baler classic. Tie-wire head and ram seal maintenance are primary items.",
    tags: ["cardboard", "paper", "plastics", "recycling center", "auto-tie"],
  },
  {
    id: "american-84hd",
    make: "American Baler",
    model: "84-HD",
    fullName: "American Baler 84-HD",
    type: "horizontal",
    tier: "industrial",
    baleWidth: 60,
    baleDepth: 60,
    baleWeightMin: 1200,
    baleWeightMax: 2400,
    motorHP: "40 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 5,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "Plastics", "Aluminum", "Steel Cans"],
    typicalUsers: ["Large MRFs", "Regional recycling operations", "Industrial plants"],
    throughput: "5–12 ton/day",
    features: ["84\" chamber", "Auto-tie", "40 HP motor", "Heavy-duty frame", "Shredder feed compatible"],
    serviceNotes: "Industrial-grade horizontal. High-tonnage operations; quarterly PM essential.",
    tags: ["cardboard", "paper", "metals", "high-volume", "industrial"],
  },
  {
    id: "american-96hd",
    make: "American Baler",
    model: "96-HD",
    fullName: "American Baler 96-HD",
    type: "horizontal",
    tier: "industrial",
    baleWidth: 72,
    baleDepth: 60,
    baleWeightMin: 1500,
    baleWeightMax: 3000,
    motorHP: "50 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 6,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["All fiber grades", "All plastic grades", "Ferrous & non-ferrous metals"],
    typicalUsers: ["Large-scale MRFs", "Steel mills", "Industrial recyclers"],
    throughput: "8–20 ton/day",
    features: ["96\" chamber", "Auto-tie", "50 HP", "Multi-material", "MRF-grade construction"],
    serviceNotes: "Top of the American Baler line. Requires dedicated maintenance schedule — Bandit recommends monthly PM.",
    tags: ["multi-material", "high-volume", "industrial", "MRF"],
  },

  // ══ HARRIS — HORIZONTAL ═══════════════════════════════════════════════════
  {
    id: "harris-hrb-1515",
    make: "Harris",
    model: "1515",
    fullName: "Harris 1515",
    type: "horizontal",
    tier: "commercial",
    baleWidth: 48,
    baleDepth: 60,
    baleWeightMin: 800,
    baleWeightMax: 1600,
    motorHP: "25 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 4,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "PET Plastics", "Aluminum Cans"],
    typicalUsers: ["Recycling centers", "Distribution hubs", "Large retailers"],
    throughput: "3–7 ton/day",
    features: ["Auto-tie wire system", "Programmable bale density", "Infeed conveyor option", "HMI controls"],
    serviceNotes: "Harris 1515 is one of the most common commercial horizontals in the SE. Excellent parts support.",
    tags: ["cardboard", "plastics", "recycling center", "auto-tie"],
  },
  {
    id: "harris-2500",
    make: "Harris",
    model: "2500",
    fullName: "Harris 2500",
    type: "horizontal",
    tier: "industrial",
    baleWidth: 60,
    baleDepth: 60,
    baleWeightMin: 1200,
    baleWeightMax: 2500,
    motorHP: "40–50 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 5,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["All paper grades", "All plastic grades", "Aluminum", "Non-ferrous metals"],
    typicalUsers: ["Large MRFs", "Industrial recyclers", "Paper mills"],
    throughput: "8–18 ton/day",
    features: ["Auto-tie", "Dual-ram option", "Touchscreen HMI", "Multiple infeed options", "High-density"],
    serviceNotes: "Harris flagship commercial baler. Dual-cylinder design; common service on tie heads and seals.",
    tags: ["multi-material", "high-volume", "industrial", "MRF"],
  },
  {
    id: "harris-6500",
    make: "Harris",
    model: "6500",
    fullName: "Harris 6500",
    type: "horizontal",
    tier: "industrial",
    baleWidth: 72,
    baleDepth: 72,
    baleWeightMin: 2000,
    baleWeightMax: 4000,
    motorHP: "75–100 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 6,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["High-volume fiber", "Mixed plastics", "Metals", "MSW streams"],
    typicalUsers: ["Large-scale MRFs", "Municipal recycling", "Industrial processing plants"],
    throughput: "15–30+ ton/day",
    features: ["Largest Harris horizontal", "Auto-tie", "100 HP capability", "MRF-grade throughput"],
    serviceNotes: "Top-of-line Harris. Reserved for high-volume operations. Requires dedicated maintenance team.",
    tags: ["high-volume", "industrial", "MRF", "municipal"],
  },
  {
    id: "harris-two-ram",
    make: "Harris",
    model: "Two-Ram Series",
    fullName: "Harris Two-Ram",
    type: "two-ram",
    tier: "industrial",
    baleWidth: 60,
    baleDepth: 72,
    baleWeightMin: 1500,
    baleWeightMax: 3500,
    motorHP: "50–100 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 6,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["Metals (ferrous & non-ferrous)", "Electronics scrap", "Rubber", "Multi-material"],
    typicalUsers: ["Scrap yards", "Metal recyclers", "Large MRFs"],
    throughput: "10–25 ton/day",
    features: ["Two-ram design", "Variable bale dimensions", "Handles hard-to-bale materials", "Heavy-duty"],
    serviceNotes: "Two-ram design allows variable bale length. Common in ferrous scrap and metals operations.",
    tags: ["metals", "scrap", "two-ram", "industrial"],
  },

  // ══ INTERNATIONAL BALER — HORIZONTAL ═════════════════════════════════════
  {
    id: "ibc-3672",
    make: "International Baler",
    model: "3672",
    fullName: "International Baler 3672",
    type: "horizontal",
    tier: "mid",
    baleWidth: 36,
    baleDepth: 48,
    baleWeightMin: 500,
    baleWeightMax: 1100,
    motorHP: "15–20 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "16 ga",
    wireFinish: "galvanized",
    wiresPerBale: 4,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "PET Bottles"],
    typicalUsers: ["Small recycling centers", "Distribution warehouses", "Grocery chains"],
    throughput: "2–5 ton/day",
    features: ["Auto-tie", "Compact horizontal footprint", "Conveyor infeed option", "US-made"],
    serviceNotes: "IBC makes balers in Jacksonville, FL — great parts availability in Southeast. Very serviceable units.",
    tags: ["cardboard", "paper", "recycling center", "auto-tie"],
  },
  {
    id: "ibc-7296",
    make: "International Baler",
    model: "7296",
    fullName: "International Baler 7296",
    type: "horizontal",
    tier: "commercial",
    baleWidth: 60,
    baleDepth: 60,
    baleWeightMin: 1000,
    baleWeightMax: 2000,
    motorHP: "30–40 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 5,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "Plastics", "Aluminum Cans"],
    typicalUsers: ["Recycling centers", "MRFs", "Industrial plants"],
    throughput: "5–12 ton/day",
    features: ["Auto-tie", "Wide chamber", "High-density bales", "US-manufactured in Jacksonville, FL"],
    serviceNotes: "Excellent SE-region support. IBC's commercial workhorse; robust frame construction.",
    tags: ["cardboard", "paper", "plastics", "recycling center", "high-volume"],
  },
  {
    id: "ibc-excel-84",
    make: "International Baler",
    model: "EXCEL 84-HD",
    fullName: "International Baler EXCEL 84-HD",
    type: "horizontal",
    tier: "industrial",
    baleWidth: 72,
    baleDepth: 60,
    baleWeightMin: 1500,
    baleWeightMax: 3000,
    motorHP: "50 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 6,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["All fiber grades", "All plastic grades", "Non-ferrous metals"],
    typicalUsers: ["Large MRFs", "Industrial recyclers", "Aluminum smelters"],
    throughput: "10–20 ton/day",
    features: ["84\" chamber", "Auto-tie", "50 HP", "Industrial-grade construction", "Dual infeed option"],
    serviceNotes: "IBC's top industrial horizontal. Built in FL; local parts support is a major operational advantage.",
    tags: ["multi-material", "high-volume", "industrial", "MRF"],
  },

  // ══ MAREN ENGINEERING — HORIZONTAL ═══════════════════════════════════════
  {
    id: "maren-24cf",
    make: "Maren Engineering",
    model: "24-CF",
    fullName: "Maren 24-CF",
    type: "horizontal",
    tier: "commercial",
    baleWidth: 48,
    baleDepth: 60,
    baleWeightMin: 700,
    baleWeightMax: 1500,
    motorHP: "25 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 4,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "Plastic Film"],
    typicalUsers: ["Paper recyclers", "Grocery distribution", "MRFs"],
    throughput: "3–8 ton/day",
    features: ["Auto-tie", "CF (channel-fed) design", "Programmable controls", "Continuous feed"],
    serviceNotes: "Maren's channel-fed design allows continuous feeding without stopping. Popular in high-speed paper operations.",
    tags: ["paper", "cardboard", "commercial", "auto-tie"],
  },
  {
    id: "maren-xt100",
    make: "Maren Engineering",
    model: "XT-100",
    fullName: "Maren XT-100",
    type: "horizontal",
    tier: "industrial",
    baleWidth: 60,
    baleDepth: 60,
    baleWeightMin: 1200,
    baleWeightMax: 2500,
    motorHP: "40 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 5,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "Plastics", "Aluminum"],
    typicalUsers: ["Large MRFs", "Paper brokers", "Industrial recyclers"],
    throughput: "8–15 ton/day",
    features: ["Auto-tie", "High-tonnage design", "40 HP motor", "PLC controls"],
    serviceNotes: "Maren's industrial line. Known for high-density bales. Parts availability varies; plan ahead.",
    tags: ["paper", "plastics", "high-volume", "industrial"],
  },

  // ══ BALEMASTER — HORIZONTAL ═══════════════════════════════════════════════
  {
    id: "balemaster-crown-40",
    make: "Balemaster",
    model: "Crown 40",
    fullName: "Balemaster Crown 40",
    type: "horizontal",
    tier: "mid",
    baleWidth: 40,
    baleDepth: 48,
    baleWeightMin: 600,
    baleWeightMax: 1200,
    motorHP: "20 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "16 ga",
    wireFinish: "galvanized",
    wiresPerBale: 4,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "Light Plastics"],
    typicalUsers: ["Small MRFs", "Distribution centers", "Grocery warehouses"],
    throughput: "2–5 ton/day",
    features: ["Auto-tie", "Compact horizontal", "20 HP motor", "Easy-access maintenance panels"],
    serviceNotes: "Good entry into commercial horizontal balers. Simple auto-tie mechanism; easy maintenance.",
    tags: ["cardboard", "paper", "commercial", "auto-tie"],
  },
  {
    id: "balemaster-crown-60",
    make: "Balemaster",
    model: "Crown 60",
    fullName: "Balemaster Crown 60",
    type: "horizontal",
    tier: "commercial",
    baleWidth: 60,
    baleDepth: 60,
    baleWeightMin: 1000,
    baleWeightMax: 2000,
    motorHP: "30 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 5,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "Plastics (PET, HDPE)", "Aluminum Cans"],
    typicalUsers: ["MRFs", "Recycling centers", "Distribution hubs"],
    throughput: "4–10 ton/day",
    features: ["Auto-tie", "High-density 30 HP", "Wide 60\" chamber", "PLC controls"],
    serviceNotes: "Commercial-grade Balemaster. Solid construction; tie head is the main PM focus.",
    tags: ["paper", "plastics", "high-volume", "commercial"],
  },

  // ══ BOLLEGRAAF — HORIZONTAL / TWO-RAM ═════════════════════════════════════
  {
    id: "bollegraaf-hbc50",
    make: "Bollegraaf",
    model: "HBC 50",
    fullName: "Bollegraaf HBC 50",
    type: "horizontal",
    tier: "commercial",
    baleWidth: 48,
    baleDepth: 60,
    baleWeightMin: 700,
    baleWeightMax: 1400,
    motorHP: "22–30 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 4,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "PET / HDPE Plastics"],
    typicalUsers: ["MRFs", "Recycling centers", "Paper brokers"],
    throughput: "3–8 ton/day",
    features: ["Auto-tie", "Dutch engineering", "High uptime design", "Remote monitoring option"],
    serviceNotes: "Premium European baler. High quality but note: some components require European sourcing.",
    tags: ["cardboard", "paper", "plastics", "commercial"],
  },
  {
    id: "bollegraaf-hbc120",
    make: "Bollegraaf",
    model: "HBC 120",
    fullName: "Bollegraaf HBC 120",
    type: "horizontal",
    tier: "industrial",
    baleWidth: 72,
    baleDepth: 72,
    baleWeightMin: 1500,
    baleWeightMax: 3500,
    motorHP: "60–100 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 6,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["All fiber grades", "All plastic grades", "Metals", "Mixed recyclables"],
    typicalUsers: ["Large MRFs", "Municipal recycling plants", "Industrial recyclers"],
    throughput: "15–30 ton/day",
    features: ["Auto-tie", "High-speed throughput", "80–100 HP", "Industry 4.0 ready", "Remote diagnostics"],
    serviceNotes: "Top-tier Bollegraaf. Requires specialized service; Bandit coordinates with Bollegraaf support on these.",
    tags: ["multi-material", "high-volume", "industrial", "MRF"],
  },
  {
    id: "bollegraaf-two-ram",
    make: "Bollegraaf",
    model: "HBC Two-Ram",
    fullName: "Bollegraaf HBC Two-Ram",
    type: "two-ram",
    tier: "industrial",
    baleWidth: 60,
    baleDepth: 72,
    baleWeightMin: 2000,
    baleWeightMax: 4000,
    motorHP: "75–125 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 6,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["Metals (ferrous & non-ferrous)", "Mixed recyclables", "Hard-to-bale materials"],
    typicalUsers: ["Large scrap yards", "Metal recyclers", "Large MRFs"],
    throughput: "15–35 ton/day",
    features: ["Two-ram variable bale length", "Top-of-market throughput", "Automated controls"],
    serviceNotes: "Elite industrial equipment. Bollegraaf-certified service strongly recommended; Bandit assists on-site.",
    tags: ["metals", "multi-material", "two-ram", "industrial"],
  },

  // ══ MACPRESSE — HORIZONTAL ════════════════════════════════════════════════
  {
    id: "macpresse-mac110",
    make: "Macpresse",
    model: "MAC 110",
    fullName: "Macpresse MAC 110",
    type: "horizontal",
    tier: "commercial",
    baleWidth: 48,
    baleDepth: 60,
    baleWeightMin: 700,
    baleWeightMax: 1500,
    motorHP: "22–30 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 4,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Newspaper (ONP)", "Mixed Paper"],
    typicalUsers: ["Newspaper plants", "Paper recyclers", "MRFs"],
    throughput: "3–7 ton/day",
    features: ["French-built channel design", "Auto-tie", "Continuous feed", "Proven newspaper baling"],
    serviceNotes: "Classic Macpresse channel baler. Very reliable in paper applications. Import parts; plan lead times.",
    tags: ["paper", "newspaper", "commercial", "auto-tie"],
  },
  {
    id: "macpresse-mac111",
    make: "Macpresse",
    model: "MAC 111",
    fullName: "Macpresse MAC 111",
    type: "horizontal",
    tier: "commercial",
    baleWidth: 60,
    baleDepth: 60,
    baleWeightMin: 1000,
    baleWeightMax: 2000,
    motorHP: "30–40 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "14 ga",
    wireFinish: "galvanized",
    wiresPerBale: 5,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "Plastics", "Aluminum"],
    typicalUsers: ["MRFs", "Industrial recyclers", "Paper mills"],
    throughput: "5–12 ton/day",
    features: ["Larger MAC 111 channel", "Auto-tie", "High-density bales", "Heavy-duty construction"],
    serviceNotes: "Macpresse's commercial workhorse. Solid performer; European import parts require planning.",
    tags: ["paper", "cardboard", "plastics", "high-volume", "commercial"],
  },

  // ══ IPS BALERS — HORIZONTAL ═══════════════════════════════════════════════
  {
    id: "ips-3660",
    make: "IPS Balers",
    model: "3660",
    fullName: "IPS Balers 3660",
    type: "horizontal",
    tier: "mid",
    baleWidth: 36,
    baleDepth: 48,
    baleWeightMin: 500,
    baleWeightMax: 1000,
    motorHP: "15–20 HP",
    wireFormat: "auto-tie-box",
    wireGauge: "16 ga",
    wireFinish: "galvanized",
    wiresPerBale: 4,
    wireProductAnchor: "auto-tie",
    commonMaterials: ["OCC / Cardboard", "Mixed Paper", "PET Plastics"],
    typicalUsers: ["Small MRFs", "Distribution centers", "Retail chains"],
    throughput: "2–5 ton/day",
    features: ["Auto-tie", "Compact horizontal", "Good value", "Easy maintenance access"],
    serviceNotes: "IPS mid-range horizontal. Growing SE dealer network; good value-to-performance ratio.",
    tags: ["cardboard", "paper", "commercial", "mid-volume"],
  },

];

// ─── DERIVED DATA ──────────────────────────────────────────────────────────────
export const ALL_MAKES = [...new Set(BALERS.map((b) => b.make))].sort();
export const WIRE_FORMAT_LABELS: Record<WireFormat, string> = {
  "single-loop": "Single Loop Bale Ties",
  "double-loop": "Double Loop Bale Ties",
  "auto-tie-box": "Auto-Tie Box Wire",
};
export const WIRE_FORMAT_DESCRIPTIONS: Record<WireFormat, string> = {
  "single-loop": "11–13 ga black annealed • 2–3 wires/bale • Vertical balers under 45\"",
  "double-loop": "11 ga black annealed • 3–5 wires/bale • Larger vertical balers 45\"+",
  "auto-tie-box": "14–16 ga galvanized • 4–6 wires/bale • Horizontal auto-tie balers",
};
export const TYPE_LABELS: Record<BalerType, string> = {
  vertical: "Vertical Baler",
  horizontal: "Horizontal Baler",
  "two-ram": "Two-Ram Baler",
};
export const TIER_LABELS: Record<BalerTier, string> = {
  entry: "Entry",
  mid: "Mid-Range",
  commercial: "Commercial",
  industrial: "Industrial",
};
export const TYPE_DESCRIPTIONS: Record<BalerType, { icon: string; description: string; typical: string }> = {
  vertical: {
    icon: "⬆️",
    description:
      "Material is loaded from the top or front and compressed downward. Bales are tied manually with single or double loop wire. Best for low-to-medium volume operations.",
    typical: "Retail stores, grocery, offices, distribution centers",
  },
  horizontal: {
    icon: "➡️",
    description:
      "Material is fed continuously into a horizontal chamber and compressed sideways. Auto-tie systems wrap bales in box wire automatically. Best for high-volume operations.",
    typical: "Recycling centers, MRFs, industrial plants, large warehouses",
  },
  "two-ram": {
    icon: "✦",
    description:
      "Dual-ram design allows variable bale lengths and handles hard-to-bale materials like metals and dense scrap. Highest throughput and bale density.",
    typical: "Scrap yards, metals recyclers, large MRFs",
  },
};
