export type MaterialCategory = "fiber" | "plastic" | "metal";
export type MetalSubcategory = "Aluminum" | "Copper" | "Brass & Red Metals" | "Ferrous" | "Lead" | "Rubber";
export type FiberSubcategory = "Corrugated" | "Mixed Paper" | "Office Paper" | "Newsprint" | "Magazines & Coated" | "Premium Grades";
export type PlasticSubcategory = "PET #1" | "HDPE #2" | "PVC #3" | "LDPE #4" | "PP #5" | "PS #6" | "Mixed";
export type ValueTier = "high" | "medium" | "low";
export type Difficulty = "Easy" | "Moderate" | "Difficult";
export type BalerType = "vertical" | "horizontal" | "both" | "none";

export interface Material {
  id: string;
  isriCode: string;
  isriName: string;
  commonName: string;
  aliases: string[];
  category: MaterialCategory;
  subcategory: string;
  icon: string;
  colorAccent: string;
  description: string;
  isriSpec: string;
  valueRange: string;
  valueTier: ValueTier;
  recyclability: "High" | "Medium" | "Low";
  processingDifficulty: Difficulty;
  // Who generates this material
  commonSources: string[];
  // Who buys it
  endBuyers: string[];
  // What it becomes after recycling
  endUses: string[];
  // Baler relevance
  balerRelevant: boolean;
  balerType: BalerType;
  // Quick-reference notes for Kevin the phone agent
  kevinNotes: string;
  // Wikimedia Commons image URL (publicly licensed)
  imageUrl?: string;
}

export const MATERIALS: Material[] = [
  // ─── FIBER ──────────────────────────────────────────────────────────────────
  {
    id: "occ",
    isriCode: "PS-11",
    isriName: "Old Corrugated Containers",
    commonName: "Cardboard / OCC",
    aliases: ["cardboard", "boxes", "corrugated", "OCC"],
    category: "fiber",
    subcategory: "Corrugated",
    icon: "📦",
    colorAccent: "#8B6914",
    description: "Used corrugated cardboard boxes. The single most traded paper grade globally. Must be free of wax coating and excessive contamination.",
    isriSpec: "Consists of corrugated containers having liners of either test liner, jute, or kraft. Prohibitive materials: 1%. Outthrows: 5%.",
    valueRange: "$50–150/ton",
    valueTier: "medium",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Retail stores", "Grocery chains", "Warehouses", "Distribution centers", "E-commerce fulfillment", "Restaurants", "Manufacturing plants"],
    endBuyers: ["Paper mills (containerboard)", "Packaging manufacturers", "International buyers (China, India, SE Asia)"],
    endUses: ["New corrugated boxes", "Paperboard", "Kraft paper", "Composite products"],
    balerRelevant: true,
    balerType: "both",
    kevinNotes: "Most common call. Ask: Is it dry? Is it waxed (wax-coated OCC is worth less — run a fingernail across it to check)? Pre-baled or loose? Vertical baler is typical for retail volumes; horizontal for high-volume distribution.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Cardboard_recycling.jpg/480px-Cardboard_recycling.jpg",
  },
  {
    id: "ds-occ",
    isriCode: "PS-12",
    isriName: "Double-Sorted Old Corrugated Containers",
    commonName: "DS OCC / Clean Cardboard",
    aliases: ["double sorted OCC", "clean cardboard", "DS OCC"],
    category: "fiber",
    subcategory: "Corrugated",
    icon: "📦",
    colorAccent: "#8B6914",
    description: "OCC that has been sorted twice to remove contaminants. Premium grade with lower contamination tolerance. Commands a price premium over standard OCC.",
    isriSpec: "Same as PS-11 but with stricter contamination limits. Prohibitives: 0.5%. Outthrows: 2%.",
    valueRange: "$70–180/ton",
    valueTier: "medium",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Retail distribution centers", "Large grocery chains", "Clean manufacturing"],
    endBuyers: ["Premium paper mills", "Containerboard producers"],
    endUses: ["High-quality containerboard", "Packaging"],
    balerRelevant: true,
    balerType: "both",
    kevinNotes: "Cleaner and higher value than standard OCC. Ask about contamination levels — if they have clean separated loads from a distribution center, this grade may apply.",
  },
  {
    id: "ncc",
    isriCode: "PS-54",
    isriName: "New Corrugated Cuttings",
    commonName: "New Corrugated Cuttings / NCC",
    aliases: ["NCC", "new corrugated", "factory corrugated", "box plant trim"],
    category: "fiber",
    subcategory: "Corrugated",
    icon: "📦",
    colorAccent: "#8B6914",
    description: "Unprinted or minimally printed corrugated cuttings and sheets generated during manufacturing. Highest corrugated grade — no end-user contamination.",
    isriSpec: "Consists of new corrugated cuttings and sheets. Free of printed corrugated. Prohibitives: 0.5%. Outthrows: 2%.",
    valueRange: "$100–250/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Box plants / corrugated manufacturers", "Converting operations", "Packaging companies"],
    endBuyers: ["Premium paper mills", "Export buyers"],
    endUses: ["High-quality containerboard", "New corrugated"],
    balerRelevant: true,
    balerType: "horizontal",
    kevinNotes: "Premium grade. Comes from box plants, not retailers. If a customer is a packaging manufacturer with clean cuttings, this could be their grade. Much higher value than regular OCC.",
  },
  {
    id: "mixed-paper",
    isriCode: "PS-1",
    isriName: "Mixed Paper",
    commonName: "Mixed Paper",
    aliases: ["junk mail", "mixed paper", "paper mix", "fiber mix"],
    category: "fiber",
    subcategory: "Mixed Paper",
    icon: "📄",
    colorAccent: "#6B7280",
    description: "A heterogeneous mixture of paper grades including mail, catalogs, magazines, and office paper. Lower value but large volume opportunity.",
    isriSpec: "Consists of a mixture of various qualities of paper not limited as to type of packing or fiber content. Prohibitives: 2%. Outthrows: 10%.",
    valueRange: "$20–80/ton",
    valueTier: "low",
    recyclability: "Medium",
    processingDifficulty: "Moderate",
    commonSources: ["Offices", "Municipal curbside programs", "Schools", "Government buildings"],
    endBuyers: ["Tissue paper mills", "Paperboard mills", "Overseas buyers"],
    endUses: ["Tissue paper", "Paperboard", "Animal bedding", "Insulation"],
    balerRelevant: true,
    balerType: "both",
    kevinNotes: "Low value but high volume. Common from offices and MRFs. Ask about contamination — food-soiled paper is prohibitive. Good candidate for vertical baler in office buildings.",
  },
  {
    id: "sop",
    isriCode: "PS-9",
    isriName: "Sorted Office Paper",
    commonName: "Sorted Office Paper / SOP",
    aliases: ["SOP", "office paper", "white paper", "computer paper"],
    category: "fiber",
    subcategory: "Office Paper",
    icon: "📄",
    colorAccent: "#6B7280",
    description: "Clean, sorted paper from office environments including letterhead, copy paper, and computer printouts. Must be free of NCR paper and food contamination.",
    isriSpec: "Consists of printed or unprinted paper, used or unused, in cut sheets, pad form or continuous rolls. Free of NCR paper. Prohibitives: 1%. Outthrows: 2%.",
    valueRange: "$80–200/ton",
    valueTier: "medium",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Corporate offices", "Law firms", "Print shops", "Banks", "Government agencies"],
    endBuyers: ["Writing paper mills", "Tissue manufacturers", "Specialty paper mills"],
    endUses: ["New office paper", "Tissue paper", "Specialty papers"],
    balerRelevant: true,
    balerType: "vertical",
    kevinNotes: "Good value for clean office paper. Common from corporate accounts. Vertical baler in back office is standard. Key question: is it mixed with food waste or NCR (no-carbon-required) paper?",
  },
  {
    id: "swl",
    isriCode: "PS-47",
    isriName: "Sorted White Ledger",
    commonName: "White Ledger / Sorted White",
    aliases: ["white ledger", "SWL", "sorted white ledger"],
    category: "fiber",
    subcategory: "Office Paper",
    icon: "📄",
    colorAccent: "#6B7280",
    description: "Premium white uncoated paper including computer paper, letterhead, and envelopes. No colored paper or non-white content. Highest office paper grade.",
    isriSpec: "Shall consist of uncoated, non-embossed white paper. Includes ledgers, tabulating cards, and computer printout. Prohibitives: 0.5%.",
    valueRange: "$120–280/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Print shops", "Banks", "Legal offices", "Medical facilities"],
    endBuyers: ["Tissue mills", "Fine paper manufacturers"],
    endUses: ["Premium tissue paper", "Writing paper", "Specialty papers"],
    balerRelevant: true,
    balerType: "vertical",
    kevinNotes: "Highest office paper grade. Must be truly white — no colored paper mixed in. Common source is print shop waste or bank/legal document disposal.",
  },
  {
    id: "onp",
    isriCode: "PS-2",
    isriName: "Sorted Residential Papers",
    commonName: "Old Newspapers / ONP",
    aliases: ["newspapers", "ONP", "newsprint", "old news"],
    category: "fiber",
    subcategory: "Newsprint",
    icon: "📰",
    colorAccent: "#6B7280",
    description: "Old newspapers and inserts as generated from residential curbside collection. Must be free of magazines and wet/moldy material.",
    isriSpec: "Consists of newspapers as typically generated at residential level including inserts. Prohibitives: 1%. Outthrows: 2%.",
    valueRange: "$30–90/ton",
    valueTier: "low",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Residential curbside programs", "MRFs", "Newspaper distributors", "Libraries"],
    endBuyers: ["Newsprint mills", "Tissue mills", "Egg carton manufacturers"],
    endUses: ["New newsprint", "Tissue paper", "Egg cartons", "Animal bedding"],
    balerRelevant: true,
    balerType: "horizontal",
    kevinNotes: "Lower value, higher volume. More common from MRF or large residential collection programs. Declining volume as print media declines. Can be baled with horizontal or vertical depending on volume.",
  },
  {
    id: "magazines",
    isriCode: "PS-32",
    isriName: "Coated Groundwood Sections",
    commonName: "Magazines & Coated Paper",
    aliases: ["magazines", "catalogs", "coated paper", "glossy paper"],
    category: "fiber",
    subcategory: "Magazines & Coated",
    icon: "📰",
    colorAccent: "#6B7280",
    description: "Coated magazines, catalogs, and glossy printed materials. Lower value due to coating chemicals. Must be sorted from uncoated paper.",
    isriSpec: "Consists of coated book stock, coated magazine stock, or coated groundwood printing papers. Prohibitives: 1%. Outthrows: 5%.",
    valueRange: "$25–70/ton",
    valueTier: "low",
    recyclability: "Medium",
    processingDifficulty: "Moderate",
    commonSources: ["Retailers", "Print distribution centers", "Offices", "MRFs"],
    endBuyers: ["Paperboard mills", "Overseas buyers"],
    endUses: ["Paperboard", "Tissue (de-coated process)"],
    balerRelevant: true,
    balerType: "vertical",
    kevinNotes: "Relatively low value. Coating reduces mill recovery. Ask if it's a clean separated stream or mixed with other paper grades — contamination hurts price significantly.",
  },
  {
    id: "hard-white",
    isriCode: "PS-8",
    isriName: "Hard White Shavings",
    commonName: "Hard White Shavings",
    aliases: ["white shavings", "envelope cuttings", "converting waste"],
    category: "fiber",
    subcategory: "Premium Grades",
    icon: "📄",
    colorAccent: "#6B7280",
    description: "White envelope and converting shavings from paper converting operations. Premium grade requiring no deinking. Very high value.",
    isriSpec: "Consists of clean white shavings and cuttings from envelope and paper converting operations. Free of printed stock. Prohibitives: 0.5%.",
    valueRange: "$150–350/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Envelope manufacturers", "Paper converters", "Printing operations"],
    endBuyers: ["Premium tissue mills", "Specialty paper manufacturers"],
    endUses: ["Premium tissue", "Fine paper", "Writing paper"],
    balerRelevant: true,
    balerType: "vertical",
    kevinNotes: "High value grade from converting operations. Uncommon caller — if you hear 'envelope plant' or 'paper converter,' flag for manual quote.",
  },
  {
    id: "kraft",
    isriCode: "PS-56",
    isriName: "Kraft",
    commonName: "Kraft Paper / Brown Bags",
    aliases: ["kraft", "brown bags", "paper bags", "kraft sacks"],
    category: "fiber",
    subcategory: "Mixed Paper",
    icon: "🛍️",
    colorAccent: "#8B6914",
    description: "Brown kraft paper including bags, sacks, and wrapping paper. Common at grocery stores and retail. Must be clean and free of food contamination.",
    isriSpec: "Consists of kraft bags, sacks, and kraft wrapping paper. Free of food-soiled material. Prohibitives: 1%.",
    valueRange: "$40–100/ton",
    valueTier: "low",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Grocery stores", "Hardware stores", "Building supply chains", "Restaurant supply distributors"],
    endBuyers: ["Kraft paper mills", "Containerboard mills"],
    endUses: ["Kraft packaging paper", "Paper bags", "Corrugated medium"],
    balerRelevant: true,
    balerType: "vertical",
    kevinNotes: "Common from grocery and retail. Often baled with OCC — ask if they're keeping it separate. Clean kraft can command its own price; mixed with OCC it falls to OCC pricing.",
  },

  // ─── PLASTICS ───────────────────────────────────────────────────────────────
  {
    id: "pet-clear",
    isriCode: "PET-C",
    isriName: "PET Bottles Clear",
    commonName: "Clear PET Bottles (#1)",
    aliases: ["water bottles", "soda bottles", "PET", "#1 plastic", "PETE"],
    category: "plastic",
    subcategory: "PET #1",
    icon: "🍶",
    colorAccent: "#60A5FA",
    description: "Clear polyethylene terephthalate bottles used for water, soda, and other beverages. No thermoforms, no caps. Most valuable PET grade.",
    isriSpec: "Baled PET bottles, clear only. No thermoforms, no colored bottles. Caps/labels must be removed or within allowance. No contamination with other resins.",
    valueRange: "$200–450/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Beverage distributors", "Hotels & hospitality", "Stadiums & venues", "MRFs", "Office buildings"],
    endBuyers: ["PET reclaimers", "Fiber manufacturers (rPET)", "Packaging companies", "Clothing manufacturers"],
    endUses: ["New PET bottles", "Polyester fiber (fleece, clothing)", "Carpet", "Strapping"],
    balerRelevant: true,
    balerType: "both",
    kevinNotes: "Ask: are they sorted clear-only, or mixed with colored/green bottles? Clear-only is higher value. Are caps and labels removed? Ask about volume — PET bales are light so expect large volumes.",
  },
  {
    id: "pet-green",
    isriCode: "PET-G",
    isriName: "PET Bottles Green",
    commonName: "Green PET Bottles (#1)",
    aliases: ["green bottles", "Sprite bottles", "green PET"],
    category: "plastic",
    subcategory: "PET #1",
    icon: "🫙",
    colorAccent: "#34D399",
    description: "Green-colored PET bottles. Lower value than clear PET due to color contamination in end products, but still a strong recyclable.",
    isriSpec: "Baled PET bottles, green color only. Free of thermoforms and other resins.",
    valueRange: "$150–350/ton",
    valueTier: "medium",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Beverage distributors", "Grocery chains", "MRFs"],
    endBuyers: ["PET reclaimers", "Fiber manufacturers"],
    endUses: ["Colored PET pellets", "Polyester fiber", "Non-food packaging"],
    balerRelevant: true,
    balerType: "both",
    kevinNotes: "Common from MRF output. Lower value than clear. Usually comes mixed in MRF bales — ask if they're sorting by color or baling mixed.",
  },
  {
    id: "pet-thermoform",
    isriCode: "PET-T",
    isriName: "PET Thermoforms",
    commonName: "PET Thermoforms / Clamshells",
    aliases: ["clamshells", "berry containers", "deli containers", "thermoforms"],
    category: "plastic",
    subcategory: "PET #1",
    icon: "🥗",
    colorAccent: "#60A5FA",
    description: "PET thermoformed packaging including clamshells, deli containers, and produce trays. Different melt point than bottles — must be kept separate.",
    isriSpec: "PET thermoformed containers and trays, sorted from bottles. No PVC contamination.",
    valueRange: "$50–200/ton",
    valueTier: "low",
    recyclability: "Medium",
    processingDifficulty: "Moderate",
    commonSources: ["Grocery deli departments", "Food distributors", "Food packaging operations"],
    endBuyers: ["Specialty PET reclaimers", "Sheet extruders"],
    endUses: ["New thermoformed packaging", "PET sheet", "Non-food containers"],
    balerRelevant: true,
    balerType: "vertical",
    kevinNotes: "Must be sorted from PET bottles — they have different processing requirements. Common from food service and grocery. Ask if they're mixing with bottles or keeping separate.",
  },
  {
    id: "hdpe-natural",
    isriCode: "HDPE-N",
    isriName: "HDPE Natural Bottles",
    commonName: "Natural HDPE Bottles (#2)",
    aliases: ["milk jugs", "natural HDPE", "white HDPE", "#2 plastic natural"],
    category: "plastic",
    subcategory: "HDPE #2",
    icon: "🥛",
    colorAccent: "#F9FAFB",
    description: "Natural (unpigmented, translucent) HDPE bottles including milk jugs and water jugs. Highest HDPE grade with best resin recovery.",
    isriSpec: "Natural color HDPE bottles only. No colored containers, no caps beyond allowance, no other resins.",
    valueRange: "$300–600/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Dairy operations", "Schools & institutions", "Grocery stores", "Food processing plants"],
    endBuyers: ["HDPE blow molders", "Pipe manufacturers", "Film manufacturers"],
    endUses: ["New bottles", "Pipe", "Lumber composite", "Toys", "Detergent bottles"],
    balerRelevant: true,
    balerType: "both",
    kevinNotes: "Highest value HDPE. Common from dairy/food processing. Must be natural (translucent white/cream) — no colored bottles. Ask if they're sorting natural from color.",
  },
  {
    id: "hdpe-color",
    isriCode: "HDPE-C",
    isriName: "HDPE Color Bottles",
    commonName: "Color HDPE Bottles (#2)",
    aliases: ["detergent bottles", "colored HDPE", "mixed HDPE", "#2 plastic color"],
    category: "plastic",
    subcategory: "HDPE #2",
    icon: "🧴",
    colorAccent: "#818CF8",
    description: "Colored HDPE bottles including detergent, shampoo, and household chemical containers. Good recyclable but lower value than natural due to mixed pigments.",
    isriSpec: "Colored HDPE bottles and containers, sorted from natural. Free of other resins and non-HDPE containers.",
    valueRange: "$150–350/ton",
    valueTier: "medium",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Grocery stores", "MRFs", "Hotels", "Healthcare facilities", "Janitorial operations"],
    endBuyers: ["HDPE reclaimers", "Lumber composite makers", "Plastic pipe manufacturers"],
    endUses: ["Mixed-color plastic lumber", "Pipes", "Landscape edging", "Non-food containers"],
    balerRelevant: true,
    balerType: "both",
    kevinNotes: "Common mixed stream. Lower value than natural HDPE. Most MRF output is color HDPE. Ask if sorted from natural — mixing loses money.",
  },
  {
    id: "ldpe-film",
    isriCode: "LDPE-F",
    isriName: "LDPE Film",
    commonName: "Plastic Film / Stretch Wrap (#4)",
    aliases: ["stretch wrap", "plastic bags", "shrink wrap", "pallet wrap", "LDPE film", "PE film"],
    category: "plastic",
    subcategory: "LDPE #4",
    icon: "🗃️",
    colorAccent: "#93C5FD",
    description: "Low-density polyethylene film including stretch wrap, plastic bags, and shrink wrap. High volume at distribution centers. Must be clean and free of food contamination.",
    isriSpec: "Clean LDPE film, free of food contamination, dirt, and other resins. Includes stretch wrap, produce bags, and retail bags.",
    valueRange: "$50–250/ton",
    valueTier: "low",
    recyclability: "Medium",
    processingDifficulty: "Moderate",
    commonSources: ["Distribution centers", "Warehouses", "Grocery stores (produce)", "Manufacturing plants", "Big-box retailers"],
    endBuyers: ["Film reclaimers", "Composite lumber manufacturers", "PE film extruders"],
    endUses: ["New stretch wrap", "Composite lumber (Trex-type)", "Trash bags", "Floor underlayment"],
    balerRelevant: true,
    balerType: "vertical",
    kevinNotes: "Huge volume from distribution centers — pallets generate tons of stretch wrap. Must be clean. Ask about volume and contamination level. Vertical baler is standard for film.",
  },
  {
    id: "pp",
    isriCode: "PP-5",
    isriName: "Polypropylene",
    commonName: "Polypropylene (#5)",
    aliases: ["PP", "#5 plastic", "yogurt containers", "bottle caps", "buckets"],
    category: "plastic",
    subcategory: "PP #5",
    icon: "🪣",
    colorAccent: "#FCD34D",
    description: "Polypropylene including tubs, buckets, lids, and automotive parts. Growing recycling market with good end-use demand.",
    isriSpec: "Clean PP containers and objects, sorted by resin. Free of other plastics.",
    valueRange: "$100–300/ton",
    valueTier: "medium",
    recyclability: "Medium",
    processingDifficulty: "Moderate",
    commonSources: ["Food manufacturers (yogurt, deli)", "Automotive operations", "Industrial operations", "Janitorial supply"],
    endBuyers: ["PP reclaimers", "Automotive parts manufacturers", "Furniture makers"],
    endUses: ["Automotive parts", "Furniture", "New containers", "Industrial fiber"],
    balerRelevant: true,
    balerType: "vertical",
    kevinNotes: "Growing demand for recycled PP. Common from food manufacturing and auto. Ask about grade — industrial PP (buckets, automotive) vs post-consumer tubs have different buyers.",
  },
  {
    id: "pvc",
    isriCode: "PVC-P",
    isriName: "Rigid PVC Pipe",
    commonName: "Rigid PVC (#3)",
    aliases: ["PVC", "vinyl pipe", "white pipe", "#3 plastic", "vinyl"],
    category: "plastic",
    subcategory: "PVC #3",
    icon: "🔧",
    colorAccent: "#6B7280",
    description: "Rigid PVC pipe and profiles from construction and plumbing. Must be kept absolutely separate — PVC contaminates every other plastic stream.",
    isriSpec: "Rigid PVC pipe and profiles only. Free of flexible PVC, painted or coated PVC, and other resins.",
    valueRange: "$150–400/ton",
    valueTier: "medium",
    recyclability: "Medium",
    processingDifficulty: "Difficult",
    commonSources: ["Plumbing contractors", "Construction demolition", "Irrigation companies", "Utilities"],
    endBuyers: ["PVC compound manufacturers", "Pipe manufacturers", "Window profile makers"],
    endUses: ["New pipe", "Window profiles", "Flooring", "Cable insulation"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "IMPORTANT: PVC cannot mix with any other plastic — even trace amounts contaminate entire loads. Ask specifically if they have pure PVC only. Construction demo sites are the typical source. Not usually baled.",
  },
  {
    id: "mixed-plastic",
    isriCode: "MRP",
    isriName: "Mixed Rigid Plastics",
    commonName: "Mixed Rigid Plastics",
    aliases: ["mixed plastics", "commingled plastic", "MRP"],
    category: "plastic",
    subcategory: "Mixed",
    icon: "♻️",
    colorAccent: "#6B7280",
    description: "Mixed rigid plastics of various resin types. Low value but diverts material from landfill. Growing buyer market as recycling technology improves.",
    isriSpec: "Mixed rigid plastic containers and objects. Must be free of film, foam, and non-plastic contamination.",
    valueRange: "$20–100/ton",
    valueTier: "low",
    recyclability: "Low",
    processingDifficulty: "Difficult",
    commonSources: ["MRFs", "Industrial facilities with mixed waste"],
    endBuyers: ["Plastic reclaimers with sorting capacity", "Composite lumber makers"],
    endUses: ["Composite lumber", "Plastic railroad ties", "Pallets"],
    balerRelevant: true,
    balerType: "vertical",
    kevinNotes: "Low value catch-all. Better to encourage sorting into individual resins if volume justifies it. Useful for facilities that can't sort — at least keeps it out of landfill.",
  },
  {
    id: "polystyrene",
    isriCode: "PS-6",
    isriName: "Polystyrene",
    commonName: "Polystyrene / EPS (#6)",
    aliases: ["styrofoam", "foam cups", "EPS", "polystyrene", "#6 plastic", "packing foam"],
    category: "plastic",
    subcategory: "PS #6",
    icon: "🧊",
    colorAccent: "#E5E7EB",
    description: "Expanded (EPS/foam) and rigid polystyrene. Limited market — most facilities don't accept it. Dense compaction required for economical transport.",
    isriSpec: "Clean EPS or rigid PS, free of food contamination and other materials.",
    valueRange: "$0–150/ton",
    valueTier: "low",
    recyclability: "Low",
    processingDifficulty: "Difficult",
    commonSources: ["Electronics packaging", "Food service", "Appliance distributors"],
    endBuyers: ["Foam densifier programs", "Limited specialty reclaimers"],
    endUses: ["Picture frames", "Rulers", "New foam"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Difficult market. Most buyers don't accept it unless it's densified. If a customer has large volumes of clean EPS from electronics packaging, refer to a foam densification program. Not our core material.",
  },

  // ─── METALS — ALUMINUM ──────────────────────────────────────────────────────
  {
    id: "ubc",
    isriCode: "Talc",
    isriName: "Post-Consumer Aluminum Can Stock (UBC)",
    commonName: "Aluminum Cans (UBC)",
    aliases: ["beer cans", "soda cans", "UBC", "used beverage containers", "aluminum cans"],
    category: "metal",
    subcategory: "Aluminum",
    icon: "🥫",
    colorAccent: "#94A3B8",
    description: "Used aluminum beverage cans. One of the most recycled materials in the world. Closed-loop recycling — a can can be back on shelves in 60 days.",
    isriSpec: "Used aluminum beverage cans, free of tin cans, bimetal cans, and non-aluminum materials. Must be reasonably free of moisture.",
    valueRange: "$1,200–1,800/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Stadiums & arenas", "Beverage distributors", "Hotels", "Recycling programs", "Convenience stores"],
    endBuyers: ["Novelis", "Constellium", "Arconic", "Aluminum sheet mills"],
    endUses: ["New aluminum beverage cans (closed loop)", "Aluminum sheet products"],
    balerRelevant: true,
    balerType: "both",
    kevinNotes: "High value, easy to process. Ask about volume (by weight or count) and how it's currently stored (loose vs. baled). UBC loses value if contaminated with tin/steel cans — ask if they're using magnets to sort.",
  },
  {
    id: "talcred",
    isriCode: "Talcred",
    isriName: "Shredded Aluminum UBC Scrap",
    commonName: "Shredded UBC",
    aliases: ["shredded cans", "densified UBC", "processed UBC"],
    category: "metal",
    subcategory: "Aluminum",
    icon: "🥫",
    colorAccent: "#94A3B8",
    description: "UBC that has been shredded for improved density and easier processing. Some contaminants removed in shredding process.",
    isriSpec: "Used beverage containers that have been shredded. Reasonably free of non-aluminum materials.",
    valueRange: "$1,300–1,900/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["MRFs with shredding capability", "Large aluminum can collectors"],
    endBuyers: ["Aluminum mills", "Sheet producers"],
    endUses: ["New aluminum sheet", "Beverage cans"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Shredded form — typically comes from MRF operations with processing equipment. Slightly higher value than unshredded UBC.",
  },
  {
    id: "taint-tabor",
    isriCode: "Taint/Tabor",
    isriName: "Aluminum Extrusions & Tubing",
    commonName: "Aluminum Extrusions / Tubing",
    aliases: ["aluminum extrusion", "aluminum tubing", "window frames", "aluminum profiles"],
    category: "metal",
    subcategory: "Aluminum",
    icon: "🔩",
    colorAccent: "#94A3B8",
    description: "Clean aluminum extrusions, tubing, and profiles from window frames, doors, and industrial applications. Free of iron and non-aluminum attachments.",
    isriSpec: "Old aluminum extrusions and tubing, free of iron, zinc, and non-metallic attachments. May include anodized and painted material.",
    valueRange: "$900–1,500/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Moderate",
    commonSources: ["Window & door manufacturers", "Construction demolition", "HVAC contractors", "Aluminum fabricators"],
    endBuyers: ["Secondary aluminum smelters", "Aluminum alloy producers"],
    endUses: ["Secondary aluminum alloys", "New extrusions"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Common from window replacement contractors and construction. Ask if attachments (screws, hinges, glass) have been removed. Iron contamination drops value significantly.",
  },
  {
    id: "tense",
    isriCode: "Tense",
    isriName: "Mixed Aluminum Castings",
    commonName: "Aluminum Castings",
    aliases: ["aluminum castings", "cast aluminum", "engine blocks", "auto castings"],
    category: "metal",
    subcategory: "Aluminum",
    icon: "⚙️",
    colorAccent: "#94A3B8",
    description: "Clean aluminum castings from automotive, industrial, and consumer applications. Multiple alloy types — value varies by alloy content.",
    isriSpec: "Clean aluminum castings. Free of iron, brass, babbitt-lined material, and non-metallics. Includes auto and airplane castings.",
    valueRange: "$800–1,400/ton",
    valueTier: "medium",
    recyclability: "High",
    processingDifficulty: "Moderate",
    commonSources: ["Auto salvage yards", "Machine shops", "Foundries", "HVAC equipment recycling"],
    endBuyers: ["Secondary aluminum smelters", "Die cast alloy producers"],
    endUses: ["Automotive castings", "Industrial die castings", "Alloy production"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Auto salvage and machine shops are the main source. Ask about cleanliness — iron inserts and steel hardware cut value. Some alloys (like 380 die cast) command premium pricing.",
  },
  {
    id: "twitch",
    isriCode: "Twitch",
    isriName: "Shredded Non-Ferrous Scrap (Zorba)",
    commonName: "Twitch / Zorba / Shredded Auto Aluminum",
    aliases: ["zorba", "twitch", "auto shred aluminum", "shredded non-ferrous"],
    category: "metal",
    subcategory: "Aluminum",
    icon: "🚗",
    colorAccent: "#94A3B8",
    description: "Shredded non-ferrous material predominantly aluminum, originating from auto shredding. Contains mixed aluminum alloys and some contaminants.",
    isriSpec: "Shredded non-ferrous scrap, predominantly aluminum, from automotive shredding. Sorted by density separation from Zorba.",
    valueRange: "$700–1,100/ton",
    valueTier: "medium",
    recyclability: "High",
    processingDifficulty: "Moderate",
    commonSources: ["Auto shredders", "Metal shredding facilities", "Auto salvage processors"],
    endBuyers: ["Secondary aluminum smelters", "Aluminum alloy producers", "International buyers"],
    endUses: ["Secondary aluminum alloys", "Automotive components"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Comes from shredding operations — not a typical small-generator material. Large volumes from auto shredders. Not commonly a Bandit customer material.",
  },

  // ─── METALS — COPPER ────────────────────────────────────────────────────────
  {
    id: "bare-bright",
    isriCode: "Barley",
    isriName: "No. 1 Copper Wire (Bare Bright)",
    commonName: "Bare Bright Copper",
    aliases: ["bare bright", "clean copper wire", "#1 copper", "bright copper wire"],
    category: "metal",
    subcategory: "Copper",
    icon: "🔌",
    colorAccent: "#F59E0B",
    description: "The highest copper grade. Clean, un-tinned, uncoated, unalloyed copper wire with no insulation. Must be bright orange in color — no oxidation allowed.",
    isriSpec: "Clean, un-tinned, uncoated, unalloyed copper wire, not smaller than No. 16 B&S gauge. Free of burnt wire. Must be bright in appearance.",
    valueRange: "$7,000–10,000/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Electricians", "Wire strippers", "Electrical contractors", "Data center decommissioning"],
    endBuyers: ["Copper rod mills", "Brass mills", "Wire and cable manufacturers"],
    endUses: ["New copper wire", "Electrical wiring", "Plumbing tube"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Highest value copper. Key question: Is the insulation fully stripped? Is it burnt? Burnt wire (from stripping by burning) is prohibited and drops to #2 or lower. Small gauge wire must be agreed upon by buyer.",
  },
  {
    id: "copper-1",
    isriCode: "Berry",
    isriName: "No. 1 Copper Wire",
    commonName: "#1 Copper",
    aliases: ["#1 copper", "clean copper", "copper wire", "berry copper"],
    category: "metal",
    subcategory: "Copper",
    icon: "🔌",
    colorAccent: "#F59E0B",
    description: "Clean, untinned, uncoated copper wire. May have slight surface oxidation but still unalloyed. Second highest copper grade after Bare Bright.",
    isriSpec: "Clean, untinned, uncoated, unalloyed copper wire and cable. Free of burnt wire. Some surface oxidation permissible.",
    valueRange: "$6,500–9,500/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Electrical contractors", "Utilities", "Manufacturing plants"],
    endBuyers: ["Copper rod mills", "Brass mills"],
    endUses: ["New copper wire", "Rod production"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Very similar to Bare Bright but allows slight oxidation. Many dealers blend Bare Bright and Berry. Ask about tinning — tinned copper drops to #2.",
  },
  {
    id: "copper-heavy",
    isriCode: "Candy",
    isriName: "No. 1 Heavy Copper",
    commonName: "#1 Heavy Copper",
    aliases: ["candy copper", "copper clippings", "bus bar", "commutator", "heavy copper"],
    category: "metal",
    subcategory: "Copper",
    icon: "🔋",
    colorAccent: "#F59E0B",
    description: "Clean copper clippings, punchings, bus bars, and commutator segments. Heavy gauge solid copper material — not wire. Free of alloys and coatings.",
    isriSpec: "Clean, uncoated, unalloyed copper clippings, punchings, bus bars, and commutator segments. Free of burnt wire. Heavy gauge.",
    valueRange: "$6,800–9,800/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Electrical manufacturers", "Transformer disassembly", "Motor shops", "Stamping operations"],
    endBuyers: ["Copper rod mills", "Brass mills", "Foundries"],
    endUses: ["New copper products", "Rod and bar", "Plumbing"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Heavy solid copper — more common from industrial operations than residential. Bus bar from electrical panels is a classic source. Near-Bare Bright value.",
  },
  {
    id: "copper-2",
    isriCode: "Birch",
    isriName: "No. 2 Copper Wire",
    commonName: "#2 Copper Wire",
    aliases: ["#2 copper", "birch copper", "oxidized copper", "mixed copper wire"],
    category: "metal",
    subcategory: "Copper",
    icon: "🔌",
    colorAccent: "#D97706",
    description: "Miscellaneous unalloyed copper wire with some oxidation, tinning, or mixed light contamination. Minimum 94% copper content. Most common copper grade.",
    isriSpec: "Miscellaneous, unalloyed copper wire. Nominal 96% copper content (minimum 94%). Free of excessive lead, iron, and non-metallics.",
    valueRange: "$6,000–8,500/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Demolition contractors", "Electricians", "HVAC contractors", "Plumbers"],
    endBuyers: ["Secondary copper refiners", "Brass mills", "Copper rod mills"],
    endUses: ["Copper rod", "Brass alloys", "Copper products"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "The catch-all for copper wire that isn't clean enough for #1. Tinned, lightly oxidized, mixed small gauges. Very common. Ask if it's truly unalloyed — copper-clad aluminum (CCA) wire looks similar but is worth much less.",
  },
  {
    id: "insulated-wire",
    isriCode: "Druid",
    isriName: "Insulated Copper Wire",
    commonName: "Insulated Copper Wire / ICW",
    aliases: ["wire with insulation", "romex", "insulated wire", "building wire", "armored cable", "BX cable"],
    category: "metal",
    subcategory: "Copper",
    icon: "🔌",
    colorAccent: "#D97706",
    description: "Copper wire with intact insulation. Priced based on copper recovery percentage. Must be stripped or sold with recovery deduction. Romex, BX, and building wire all qualify.",
    isriSpec: "No. 1 bare, uncoated, unalloyed copper wire with various insulation types. Sold on sample or recovery basis by mutual agreement.",
    valueRange: "$1,500–5,000/ton",
    valueTier: "medium",
    recyclability: "High",
    processingDifficulty: "Moderate",
    commonSources: ["Demolition contractors", "Electricians", "Utilities", "Data center decommissioning", "HVAC contractors"],
    endBuyers: ["Wire chopping plants", "Secondary copper refiners"],
    endUses: ["Recovered copper for wire and alloys", "Plastic insulation recovery"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Value depends on copper recovery % — ask what type of wire (Romex has different recovery than armored BX). Can be stripped to bare bright for much higher value. Wire chopping plants buy it in bulk. Recovery typically ranges 50-80%.",
  },

  // ─── METALS — BRASS ─────────────────────────────────────────────────────────
  {
    id: "yellow-brass",
    isriCode: "Honey",
    isriName: "Yellow Brass",
    commonName: "Yellow Brass",
    aliases: ["brass", "yellow brass", "cartridge brass", "plumbing brass"],
    category: "metal",
    subcategory: "Brass & Red Metals",
    icon: "🔩",
    colorAccent: "#FBBF24",
    description: "Copper-zinc alloy (60–70% copper). Includes fittings, valves, plumbing fixtures, and yellow brass solids. Free of aluminum and iron attachments.",
    isriSpec: "Yellow brass scrap including solids, rod turnings, and mixed yellow brass. Free of aluminum, iron, and excessive dirt.",
    valueRange: "$3,500–5,500/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Plumbing contractors", "HVAC companies", "Ammunition manufacturers", "Locksmiths", "Plumbing supply distributors"],
    endBuyers: ["Brass mills", "Foundries", "Copper alloy producers"],
    endUses: ["New brass fittings", "Plumbing fixtures", "Brass rod and sheet", "Ammunition casings"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Very common from plumbing and HVAC contractors. Ask about iron attachments (shut-off valve stems are often steel). Yellow color distinguishes from red brass (higher copper content).",
  },
  {
    id: "red-brass",
    isriCode: "Ocean",
    isriName: "Red Brass",
    commonName: "Red Brass",
    aliases: ["red brass", "semi-red brass", "plumbing red brass", "bronze"],
    category: "metal",
    subcategory: "Brass & Red Metals",
    icon: "🔩",
    colorAccent: "#F97316",
    description: "Higher copper content brass (80–85% copper). Reddish color. More valuable than yellow brass. Includes water meters, valves, and fittings.",
    isriSpec: "Red brass scrap with minimum 80% copper content. Free of aluminum, iron, and non-metallics.",
    valueRange: "$4,000–6,000/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Utilities (water meters)", "Plumbing contractors", "Fire suppression systems"],
    endBuyers: ["Brass mills", "Copper alloy producers"],
    endUses: ["Plumbing fittings", "Marine hardware", "Architectural bronze"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Reddish color is the key identifier. Higher value than yellow brass due to copper content. Water meters (utilities) are a classic source. Confirm it's not just surface oxidation on yellow brass.",
  },

  // ─── METALS — FERROUS ───────────────────────────────────────────────────────
  {
    id: "hms1",
    isriCode: "200",
    isriName: "No. 1 Heavy Melting Steel",
    commonName: "HMS #1 / Heavy Melt",
    aliases: ["HMS 1", "heavy melt", "heavy steel", "structural steel", "HMS #1"],
    category: "metal",
    subcategory: "Ferrous",
    icon: "🏗️",
    colorAccent: "#6B7280",
    description: "Wrought iron and steel scrap, 1/4 inch and over in thickness. Individual pieces not over 60×24 inches. Clean and free of non-metallics. The benchmark ferrous grade.",
    isriSpec: "Wrought iron and/or steel scrap, 1/4\" and over in thickness. Not over 60\"x24\" (charging box size). Free of cast iron, non-metallics, and excessive rust.",
    valueRange: "$300–500/ton",
    valueTier: "medium",
    recyclability: "High",
    processingDifficulty: "Moderate",
    commonSources: ["Steel fabricators", "Manufacturing plants", "Demolition contractors", "Structural steel operations"],
    endBuyers: ["Steel mills (EAF)", "Foundries", "International buyers"],
    endUses: ["New steel via electric arc furnace", "Structural steel", "Rebar"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Standard heavy steel benchmark. Thickness is key — must be 1/4\" or thicker. Common from fab shops and demolition. Ask about size — oversized needs torching.",
  },
  {
    id: "hms2",
    isriCode: "201",
    isriName: "No. 2 Heavy Melting Steel",
    commonName: "HMS #2",
    aliases: ["HMS 2", "HMS #2", "light iron", "thin steel"],
    category: "metal",
    subcategory: "Ferrous",
    icon: "🏗️",
    colorAccent: "#6B7280",
    description: "Thinner steel and iron scrap including sheet material. Can include auto body sheet and lighter gauge industrial scrap. Lower value than HMS #1.",
    isriSpec: "Black and galvanized steel scrap, thinner than 1/4\" gauge. May include old auto body sheet. Free of autos with engines and transmissions.",
    valueRange: "$260–450/ton",
    valueTier: "medium",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Auto salvage yards", "Appliance recyclers", "HVAC contractors", "Sheet metal shops"],
    endBuyers: ["Steel mills", "Export buyers"],
    endUses: ["New steel", "Sheet products"],
    balerRelevant: true,
    balerType: "horizontal",
    kevinNotes: "Lighter steel — sheet metal, thin auto body panels. Often baled by horizontal auto balers. Common from auto salvage and appliance recycling.",
  },
  {
    id: "busheling",
    isriCode: "207",
    isriName: "No. 1 Busheling",
    commonName: "#1 Busheling / Factory Bundles",
    aliases: ["busheling", "factory steel", "steel punchings", "new steel scrap"],
    category: "metal",
    subcategory: "Ferrous",
    icon: "🏭",
    colorAccent: "#6B7280",
    description: "Clean steel scrap not exceeding 12 inches in any dimension. New factory busheling including sheet clippings and stampings. Highest steel grade — no old scrap.",
    isriSpec: "Clean steel scrap, not exceeding 12\" in any dimension. Includes new factory busheling: sheet clippings, stampings. Free of old auto body scrap.",
    valueRange: "$350–550/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Metal stamping plants", "Automotive manufacturing", "Steel service centers", "Appliance manufacturers"],
    endBuyers: ["EAF steel mills", "Specialty steel producers"],
    endUses: ["High-quality new steel", "Automotive sheet steel"],
    balerRelevant: true,
    balerType: "horizontal",
    kevinNotes: "Premium clean factory steel — comes from stamping and fabrication operations, not demo or salvage. If a manufacturer says they have 'clean steel punchings', this is likely the grade.",
  },
  {
    id: "shredded",
    isriCode: "210",
    isriName: "Shredded Scrap",
    commonName: "Shredded Steel",
    aliases: ["shredded scrap", "auto shred", "shredded steel", "zorba fines"],
    category: "metal",
    subcategory: "Ferrous",
    icon: "🚗",
    colorAccent: "#6B7280",
    description: "Homogeneous iron and steel scrap processed through a shredder. Originates from automobiles and mixed steel. Uniform density for easy charging.",
    isriSpec: "Homogeneous iron and steel scrap, magnetically separated, originating from shredding. Average density 50+ lbs/cubic foot.",
    valueRange: "$280–450/ton",
    valueTier: "medium",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Auto shredders", "Metal shredding facilities"],
    endBuyers: ["EAF steel mills", "Export buyers"],
    endUses: ["New steel products"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Comes from shredding operations. Not typically a small-generator material. Large-scale auto recyclers are the main source.",
  },
  {
    id: "tin-cans",
    isriCode: "213",
    isriName: "Steel Can Bundles",
    commonName: "Tin Cans / Steel Cans",
    aliases: ["tin cans", "food cans", "steel cans", "soup cans", "bimetal cans"],
    category: "metal",
    subcategory: "Ferrous",
    icon: "🥫",
    colorAccent: "#9CA3AF",
    description: "Tin-coated steel food and beverage cans. The tin coating (less than 0.25% by weight) is removed during steelmaking. Must be free of aluminum cans.",
    isriSpec: "Old tin-coated steel cans, baled or loose. Free of aluminum cans. Tin coating max 0.25% by weight.",
    valueRange: "$100–250/ton",
    valueTier: "low",
    recyclability: "High",
    processingDifficulty: "Easy",
    commonSources: ["Food manufacturers", "Grocery chains", "School cafeterias", "Military food supply"],
    endBuyers: ["Steel mills", "Tinplate producers"],
    endUses: ["New steel", "New tinplate"],
    balerRelevant: true,
    balerType: "horizontal",
    kevinNotes: "Key question: Are any aluminum cans mixed in? Easy test — magnets stick to steel cans, not aluminum. Food processors and large kitchens generate this. Often baled.",
  },
  {
    id: "cast-iron",
    isriCode: "220",
    isriName: "Cast Iron",
    commonName: "Cast Iron",
    aliases: ["cast iron", "iron", "engine block", "cast", "gray iron"],
    category: "metal",
    subcategory: "Ferrous",
    icon: "⚓",
    colorAccent: "#374151",
    description: "Clean cast iron including columns, pipes, and machine castings. Free of brake shoes and malleable iron. Heavy, dense material.",
    isriSpec: "Clean cast iron including columns, pipes, plates, and castings. Free of stove plate, brake shoes, and malleable iron.",
    valueRange: "$150–300/ton",
    valueTier: "low",
    recyclability: "High",
    processingDifficulty: "Moderate",
    commonSources: ["Auto repair shops (rotors, drums)", "Plumbing (cast iron pipe)", "Machine shops", "Industrial equipment decommissioning"],
    endBuyers: ["Foundries", "Iron casting producers"],
    endUses: ["New iron castings", "Machinery components"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Dull gray fracture face is characteristic. Brake rotors and drums from auto shops are a very common source. Heavy — weight is the friend here. Ask about grade purity (no brake shoes).",
  },
  {
    id: "stainless-304",
    isriCode: "SS304",
    isriName: "Stainless Steel 304",
    commonName: "Stainless Steel 304",
    aliases: ["stainless", "304 stainless", "SS", "stainless steel", "18-8 stainless"],
    category: "metal",
    subcategory: "Ferrous",
    icon: "⚙️",
    colorAccent: "#D1D5DB",
    description: "Austenitic stainless steel (18% chromium, 8% nickel). Most common stainless grade. Non-magnetic. High value due to nickel and chromium content.",
    isriSpec: "304 (18-8) austenitic stainless steel. Minimum analysis: 18% Cr, 8% Ni. Free of coated or contaminated material.",
    valueRange: "$1,200–2,000/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Moderate",
    commonSources: ["Food processing equipment", "Restaurant equipment", "Medical device manufacturers", "Chemical plants", "Kitchen fabricators"],
    endBuyers: ["Stainless steel mills", "Specialty alloy producers"],
    endUses: ["New stainless steel", "Food equipment", "Medical instruments"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Non-magnetic test: unlike carbon steel, 304 stainless barely attracts magnets (or not at all). Very high value. Ask about grade certainty — 316 (marine grade, has molybdenum) is worth even more. Food equipment is prime source.",
  },

  // ─── METALS — LEAD ──────────────────────────────────────────────────────────
  {
    id: "soft-lead",
    isriCode: "Rains",
    isriName: "Soft Lead",
    commonName: "Soft Lead / Battery Lead",
    aliases: ["lead", "battery lead", "lead acid", "wheel weights", "soft lead"],
    category: "metal",
    subcategory: "Lead",
    icon: "🔋",
    colorAccent: "#6B7280",
    description: "Soft metallic lead from batteries, cable sheathing, and sheet lead. Hazardous material — requires proper handling and licensed recyclers.",
    isriSpec: "Soft lead including battery lead, cable sheathing, and lead sheet. Free of dross and non-metallic contaminants. HAZMAT handling required.",
    valueRange: "$1,500–2,000/ton",
    valueTier: "high",
    recyclability: "High",
    processingDifficulty: "Difficult",
    commonSources: ["Auto repair shops (batteries)", "Utilities (cable)", "Roofing (flashing)", "Shooting ranges"],
    endBuyers: ["Lead smelters", "Battery manufacturers", "Lead product producers"],
    endUses: ["New lead-acid batteries", "Radiation shielding", "Shot and ammunition"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "HAZMAT — must go to licensed lead recycler. Do NOT handle without proper procedures. Car batteries are the most common source. Ask if batteries are intact or broken — broken batteries require special handling.",
  },
  {
    id: "hard-lead",
    isriCode: "Rails",
    isriName: "Hard Lead",
    commonName: "Hard Lead / Antimonial Lead",
    aliases: ["hard lead", "antimonial lead", "rails lead", "battery plates"],
    category: "metal",
    subcategory: "Lead",
    icon: "🔋",
    colorAccent: "#6B7280",
    description: "Lead-antimony alloy (hard lead) from battery plates and type metal. Slightly harder than pure lead. Also requires licensed handling.",
    isriSpec: "Hard lead (antimonial lead) from battery plates and similar sources. Minimum 94% lead with antimony content. Licensed handler required.",
    valueRange: "$1,400–1,900/ton",
    valueTier: "medium",
    recyclability: "High",
    processingDifficulty: "Difficult",
    commonSources: ["Battery manufacturers", "Battery recyclers", "Printing operations (type metal)"],
    endBuyers: ["Lead smelters", "Battery manufacturers"],
    endUses: ["New battery plates", "Ammunition"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Same HAZMAT cautions as soft lead. Battery plate lead is the main source. Refer to a licensed lead recycler — this isn't a material we handle directly.",
  },

  // ─── RUBBER ─────────────────────────────────────────────────────────────────
  {
    id: "whole-tires",
    isriCode: "WTR",
    isriName: "Whole Used Tires",
    commonName: "Scrap Tires / Whole Tires",
    aliases: ["tires", "scrap tires", "used tires", "waste tires"],
    category: "metal",
    subcategory: "Rubber",
    icon: "🛞",
    colorAccent: "#374151",
    description: "Whole used tires from passenger vehicles, trucks, and equipment. Regulated in most Southeast states — must use licensed tire recyclers.",
    isriSpec: "Whole used tires, any size. State-regulated — must comply with Southeast US tire disposal regulations. Licensed haulers required.",
    valueRange: "$30–80/ton",
    valueTier: "low",
    recyclability: "Medium",
    processingDifficulty: "Difficult",
    commonSources: ["Auto repair shops", "Tire retailers", "Fleet operations", "Auto salvage yards"],
    endBuyers: ["Tire-derived fuel (TDF) processors", "Crumb rubber manufacturers", "Civil engineering projects"],
    endUses: ["Tire-derived fuel", "Crumb rubber (playground surfaces)", "Retaining walls", "Road fill"],
    balerRelevant: true,
    balerType: "horizontal",
    kevinNotes: "State regulated in FL, GA, AL, SC, NC, TN — must use licensed tire recycler. Auto shops are the biggest source. Ask about quantity and whether on-rims or off-rims. Horizontal tire balers compress tires for transport efficiency.",
  },
  {
    id: "crumb-rubber",
    isriCode: "CRM",
    isriName: "Crumb Rubber",
    commonName: "Crumb Rubber / Ground Rubber",
    aliases: ["crumb rubber", "ground rubber", "rubber granules", "tire crumb"],
    category: "metal",
    subcategory: "Rubber",
    icon: "🏈",
    colorAccent: "#374151",
    description: "Mechanically processed tire rubber, ground into granules. High value compared to whole tires due to processing. Used in sport surfaces and rubber products.",
    isriSpec: "Tire rubber processed to crumb form, mesh size by agreement. Free of steel wire (for passenger tires) or with steel noted (truck tires).",
    valueRange: "$100–300/ton",
    valueTier: "medium",
    recyclability: "Medium",
    processingDifficulty: "Moderate",
    commonSources: ["Tire shredding operations", "Tire recyclers"],
    endBuyers: ["Sports field manufacturers", "Rubber product makers", "Asphalt producers"],
    endUses: ["Synthetic turf infill", "Playground safety surfaces", "Rubber-modified asphalt", "Molded rubber products"],
    balerRelevant: false,
    balerType: "none",
    kevinNotes: "Post-processed tire material — comes from tire shredding/grinding operations, not end users. Higher value than whole tires.",
  },
];

// Flat list of all subcategories
export const SUBCATEGORIES = {
  fiber: ["Corrugated", "Mixed Paper", "Office Paper", "Newsprint", "Magazines & Coated", "Premium Grades"],
  plastic: ["PET #1", "HDPE #2", "LDPE #4", "PP #5", "PVC #3", "PS #6", "Mixed"],
  metal: ["Aluminum", "Copper", "Brass & Red Metals", "Ferrous", "Lead", "Rubber"],
};

export const CATEGORY_META = {
  fiber: {
    label: "Fiber & Paper",
    description: "Paper and cardboard materials graded by ISRI Paper Stock (PS) specifications.",
    icon: "📦",
    color: "#8B6914",
    stat: "Used cardboard can become a new box in 14 days",
  },
  plastic: {
    label: "Plastics",
    description: "Plastic resins identified by Resin Identification Code (RIC #1–7).",
    icon: "♻️",
    color: "#3B82F6",
    stat: "Recycled PET bottles become polyester clothing in 6 weeks",
  },
  metal: {
    label: "Metals",
    description: "Ferrous and non-ferrous metals graded by ISRI Scrap Specifications Circular.",
    icon: "🔩",
    color: "#94A3B8",
    stat: "Aluminum cans return to shelves in just 60 days",
  },
};
